(define (divisible? big small)
  (= (remainder big small) 0))

(define (leap-year? year)
  (if (divisible? year 4)
    (if (divisible? year 100) (divisible? year 400) #t) #f))

(define (31days? month)
  (cond ((= month 2) #f)
	((= month 4) #f)
	((= month 6) #f)
	((= month 9) #f)
	((= month 11) #f)
	 (else #t)))

(define (valid-date? month day year)
  (cond ((<= year 0) #f)
	((<= month 0) #f)
	((<= day 0) #f)
	((> month 12) #f)
	((> day 31) #f)
	((= day 31) (31days? month))
	((and (= month 2) (= day 29)) (leap-year? year))
	((and (= month 2) (> day 28)) #f)
	((< day 31) #t)
	(else #f)))
