(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance 
                     (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
      (cond ((not (eq? p password))
             (lambda (.x) "Password provided does not match account password"))
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'password) password)
            (else (error "Unknown request: 
                         MAKE-ACCOUNT" m))))
  dispatch)

(define (make-joint account old-pswd new-pswd)
  (define (dispatch p m)
    (cond ((eq? p new-pswd) (account old-pswd m))
          (else (lambda (.x) "Password provided does not match joint account password")) ))
  (if (eq? old-pswd (account old-pswd 'password))
    dispatch
    (error "Password does not match old account password") ))
